### ISSUE TITLE
Linefish import 

### ISSUE THREAD

**Issue by Dewidine** [SANBIBiodiversityforLife/species#114]
@rukayaj Need to check reference issues so references do not have authors. Need to check import from Seakeys if possible, not sure whether data was not captured or whether somehow its not importing correctly.

**Comment by Dewidine** [comment]
Checked source, it was captured, so some issues with import.

**Comment by rukayaj** [comment]
There are so many things I need to do asap for NSSL but will try squeeze it in this week.

**Comment by strumaria** [comment]
Rukaya there are also random strange characters coming into the linefish texts e.g. 5.	Funny Â e.g Spotted Grunter. Morphology seems to be cut off. 

Albula oligolepis check for weird symbols after name in italics. Platycephalus indicus  Vetchâs

**Comment by rukayaj** [comment]
Ok I've fixed the references missing authors and removed as many of the random characters as I can find. Craig's character encoding script doesn't fix them, I think it's fastest to remove them manually, I must just remember to do it over again next time we do an import. Find and replace €™ => ". I haven't put the changes up yet because I might as well fix all the other import scripts first. 

Can't find any examples of where morphology is cut off, can you send me some?

**Comment by Dewidine** [comment]
@rukayaj  please send me a link to Seakeys, the morphology is not part of the assessment docs, so I can't check whether there is text missing. I need to access Seakeys, if you haven't gotten  back to me I will check with Prideel. And give feedback.

**Comment by rukayaj** [comment]
It's seakeys.sanbi.org @Dewidine

**Comment by rukayaj** [comment]
Ok we found that Tilla probably got confused because of the funny character appearing after the full stop - morphology is NOT being cut off. So this issue can be closed as soon as I upload everything to the live site.
