### ISSUE TITLE
_new in species names

### ISSUE THREAD

**Issue by rukayaj** [SANBIBiodiversityforLife/species#91]
@Dewidine  is manually checking all species in every SIS group which has suffixed with _new or _old. If there's a duplicate she changes the name, and she will send me a list of all the names she has changed. Once she has done that I will use the list to remove the _new or _old suffixes. This will fix the broken images in the website.

**Comment by Dewidine** [comment]
@rukayaj These are the only three taxa with issues, and there are no duplicates. The "old" was fixed in SIS, so we don't have to do anything. 

Group | Taxon_ID | Action
-- | -- | --
Amphibia | 107580991 | Removed "new" from species name in taxonomy spreadsheet
Amphibia | 112716154 | Removed "new" from species name in taxonomy spreadsheet
Amphibia | 45331440 | Removed "new" from species name in taxonomy spreadsheet

**Comment by Dewidine** [comment]
@rukayaj I'm closing this issue, the, it has been resolved in SIS, so with the new data export, there are no "new" in the name.
